let C={movies:[],tv:[]};
const DEFAULT=()=>({schema:2,tmdbKey:"",custom:{movies:[],tv:[]},movie:{phase:"setup",a:{},list:[],round:0},tv:{phase:"setup",a:{},list:[],round:0}});
let S=(()=>{try{let x=JSON.parse(localStorage.getItem("hf-v1.2")||localStorage.getItem("hf-v1")||"null");return x?{...DEFAULT(),...x,custom:x.custom||{movies:[],tv:[]},tmdbKey:x.tmdbKey||""}:DEFAULT()}catch(e){return DEFAULT()}})(),view="home",tab="list",expanded={},searchTimer=0,searchSeq=0;
const save=()=>localStorage.setItem("hf-v1.2",JSON.stringify(S));
const cfg=k=>k==="movie"?{name:"Movie Hundo",size:100,key:"movies",noun:"films",tmdb:"movie"}:{name:"TV Fiddy",size:50,key:"tv",noun:"series",tmdb:"tv"};
const st=k=>S[k], all=k=>[...(C[cfg(k).key]||[]),...(S.custom[cfg(k).key]||[])], A=(k,id)=>st(k).a[id]||(st(k).a[id]={status:"",rating:0,comment:"",source:""});
const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
fetch("catalog.json").then(r=>r.json()).then(x=>{C=x;render()}).catch(()=>render());
function go(k){view=k;tab="list";render()}
function status(k,id,v){let a=A(k,id);a.status=v;if(v!=="seen")a.rating=0;save();render()}
function rate(k,id,n){let a=A(k,id);a.status="seen";a.rating=n;save();render()}
function toggleComment(id){expanded[id]=!expanded[id];render()}
function comment(k,id,v){A(k,id).comment=v;save()}
function sentiment(s){s=(s||"").toLowerCase();let n=0;["love","loved","great","amazing","brilliant","best","excellent","funny","tense","clever"].forEach(w=>s.includes(w)&&(n+=.6));["shit","rubbish","terrible","awful","boring","dragged","too long","went downhill","bad after","gave up"].forEach(w=>s.includes(w)&&(n-=.7));return n}
function scores(k){let g={};Object.entries(st(k).a).forEach(([id,a])=>{let x=all(k).find(z=>z.id===id);if(!x)return;let v=a.status==="nope"?-2.5:a.status==="seen"?((a.rating||3)-3)*1.3+sentiment(a.comment)*1.7:0;(x.genre||"Other").split(" / ").forEach(q=>g[q]=(g[q]||0)+v)});return g}
function generate(k,carry=[]){let s=st(k),g=scores(k),keep=new Set(carry),seen=new Set(Object.entries(s.a).filter(([_,a])=>a.status==="seen").map(([id])=>id));let pool=all(k).filter(x=>!seen.has(x.id)&&!keep.has(x.id)&&A(k,x.id).status!=="nope");pool.sort((x,y)=>(y.genre||"").split(" / ").reduce((n,q)=>n+(g[q]||0),0)-(x.genre||"").split(" / ").reduce((n,q)=>n+(g[q]||0),0));s.list=[...carry,...pool.slice(0,cfg(k).size-carry.length).map(x=>x.id)];s.phase="list";s.round++;save();render()}
function regen(k){if(st(k).phase==="setup")return generate(k);let left=st(k).list.filter(id=>["","not"].includes(A(k,id).status));if(!left.length)return generate(k);window.keepSet=new Set();document.body.insertAdjacentHTML("beforeend",`<div class="overlay" id="ov"><div class="sheet"><h2>Before we refresh…</h2><p>${left.length} unwatched ${cfg(k).noun} remain. Pick any you want carried forward.</p>${left.map(id=>{let x=all(k).find(z=>z.id===id);return x?`<label class="carry"><input type="checkbox" onchange="this.checked?keepSet.add('${id}'):keepSet.delete('${id}')"><span><b>${esc(x.title)}</b><div class="meta">${esc(x.genre)}</div></span></label>`:""}).join("")}<div class="controls"><button class="ctrl" onclick="ov.remove()">Cancel</button><button class="ctrl on" onclick="let q=[...keepSet];ov.remove();generate('${k}',q)">Generate new list</button></div></div></div>`)}
function stars(k,x){let a=A(k,x.id);return a.status==="seen"?`<div class="ratingline">${[1,2,3,4,5].map(n=>`<button class="star ${a.rating>=n?"on":""}" onclick="rate('${k}','${x.id}',${n})">★</button>`).join("")}</div><button class="note" onclick="toggleComment('${x.id}')">${a.comment?"Edit comment":"Add a comment"}</button>${expanded[x.id]?`<div class="commentbox"><textarea class="notearea" oninput="comment('${k}','${x.id}',this.value)" placeholder="What worked? What didn't? Seasons, plot, tone, pacing…">${esc(a.comment)}</textarea><div class="saved">Saved automatically</div></div>`:""}`:""}
function row(k,x,n){let a=A(k,x.id);return `<div class="row"><div class="num">${String(n).padStart(2,"0")}</div><div><div class="title">${esc(x.title)} ${x.year?`<span class="year">${esc(x.year)}</span>`:""}</div><div class="meta">${esc(x.genre||"Other")}${x.source==="tmdb"?" · online":""}</div><div class="controls"><button class="ctrl ${a.status==="seen"?"on":""}" onclick="status('${k}','${x.id}','seen')">Seen</button><button class="ctrl ${a.status==="not"?"on":""}" onclick="status('${k}','${x.id}','not')">Not seen</button><button class="ctrl nope ${a.status==="nope"?"on":""}" onclick="status('${k}','${x.id}','nope')">Not interested</button></div>${stars(k,x)}</div></div>`}
function hist(k){return all(k).filter(x=>A(k,x.id).status==="seen")}
function histrow(k,x){let a=A(k,x.id),key="h"+x.id;return `<div class="hist"><button onclick="expanded['${key}']=!expanded['${key}'];render()"><b>${esc(x.title)}</b><span style="float:right">${a.rating?"★".repeat(a.rating):"Seen"}</span></button>${expanded[key]?`<div class="histbody"><div class="meta">${esc(x.genre)}</div>${stars(k,x)}${a.comment?`<div class="historycomment">${esc(a.comment)}</div>`:""}</div>`:""}</div>`}
function backup(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"}));a.download="hundo-fiddy-v1.2-backup.json";a.click();toast("Backup created")}
function toast(t){document.body.insertAdjacentHTML("beforeend",`<div class="toast">${esc(t)}</div>`);setTimeout(()=>document.querySelector(".toast")?.remove(),1800)}
function settings(){document.body.insertAdjacentHTML("beforeend",`<div class="overlay" id="set"><div class="sheet settings"><h2>Settings</h2><p class="meta">Online search uses TMDB. Paste your TMDB API Read Access Token below. It stays on this device.</p><label class="settinglabel">TMDB API Read Access Token</label><input id="tmdb" class="search" type="password" value="${esc(S.tmdbKey)}" placeholder="Paste token here"><button onclick="S.tmdbKey=document.getElementById('tmdb').value.trim();save();toast('Online search saved')">Save online search</button><button onclick="backup()">Backup everything</button><button onclick="document.getElementById('rf').click()">Restore backup</button><input id="rf" hidden type="file" accept=".json" onchange="restore(this)"><button class="danger" onclick="resetSide('movie')">Reset Movie Hundo</button><button class="danger" onclick="resetSide('tv')">Reset TV Fiddy</button><button class="danger" onclick="resetAll()">Reset everything</button><button onclick="set.remove()">Close</button></div></div>`)}
function restore(el){let r=new FileReader();r.onload=()=>{try{S={...DEFAULT(),...JSON.parse(r.result)};S.custom=S.custom||{movies:[],tv:[]};save();set.remove();render();toast("Restored")}catch(e){alert("Invalid backup")}};r.readAsText(el.files[0])}
function fresh(){return {phase:"setup",a:{},list:[],round:0}}
function resetSide(k){if(confirm("Reset "+cfg(k).name+"?")){S[k]=fresh();save();set.remove();render()}}
function resetAll(){if(confirm("Reset everything?")){let key=S.tmdbKey;S=DEFAULT();S.tmdbKey=key;save();set.remove();view="home";render()}}
function manual(k,id){let s=st(k);if(!s.list.includes(id))s.list.push(id);A(k,id).source="manual";save();render();toast("Added to "+cfg(k).name)}
function addRemote(k,obj){let bucket=S.custom[cfg(k).key],id=`tmdb-${cfg(k).tmdb}-${obj.id}`;if(!bucket.some(x=>x.id===id))bucket.push({id,title:obj.title||obj.name,year:(obj.release_date||obj.first_air_date||"").slice(0,4),genre:(obj.genre_names||[]).join(" / ")||"Other",source:"tmdb",tmdbId:obj.id});manual(k,id)}
async function onlineSearch(k,q,seq){if(!S.tmdbKey){rows.insertAdjacentHTML("beforeend",`<div class="onlinehint">Want the whole internet catalogue? <button onclick="settings()">Connect online search</button></div>`);return}try{let type=cfg(k).tmdb,url=`https://api.themoviedb.org/3/search/${type}?query=${encodeURIComponent(q)}&include_adult=false&language=en-US&page=1`,r=await fetch(url,{headers:{Authorization:`Bearer ${S.tmdbKey}`,accept:"application/json"}});if(!r.ok)throw new Error("TMDB "+r.status);let data=await r.json();if(seq!==searchSeq)return;let ids=[...new Set((data.results||[]).flatMap(x=>x.genre_ids||[]))];let gm={};if(ids.length){let gr=await fetch(`https://api.themoviedb.org/3/genre/${type}/list?language=en`,{headers:{Authorization:`Bearer ${S.tmdbKey}`,accept:"application/json"}});if(gr.ok)(await gr.json()).genres.forEach(g=>gm[g.id]=g.name)}let hits=(data.results||[]).slice(0,12).map(x=>({...x,genre_names:(x.genre_ids||[]).map(id=>gm[id]).filter(Boolean)}));if(seq!==searchSeq)return;let localIds=new Set(all(k).map(x=>x.id));let html=hits.map(x=>{let id=`tmdb-${type}-${x.id}`,exists=localIds.has(id);return `<div class="row online"><div class="num">+</div><div><div class="title">${esc(x.title||x.name)} <span class="year">${esc((x.release_date||x.first_air_date||"").slice(0,4))}</span></div><div class="meta">${esc(x.genre_names.join(" / ")||"Online result")}</div><button class="ctrl on" ${exists?"disabled":""} onclick='addRemote("${k}",${JSON.stringify(x).replace(/'/g,"&#39;")})'>${exists?"Already added":"Add to my "+cfg(k).name}</button></div></div>`}).join("");rows.insertAdjacentHTML("beforeend",`<div class="onlinehead">Online results</div>${html||'<div class="empty small">No online matches.</div>'}`)}catch(e){if(seq===searchSeq)rows.insertAdjacentHTML("beforeend",`<div class="onlinehint error">Online search couldn't connect. Check the TMDB token in Settings.</div>`)}}
function search(k,q){q=q.trim();let own=st(k).phase==="setup"?all(k).slice(0,40):st(k).list.map(id=>all(k).find(x=>x.id===id)).filter(Boolean);if(!q){rows.innerHTML=own.map((x,i)=>row(k,x,i+1)).join("");return}let low=q.toLowerCase(),m=own.filter(x=>x.title.toLowerCase().includes(low));let catalogue=all(k).filter(x=>x.title.toLowerCase().includes(low)&&!own.some(o=>o.id===x.id)).slice(0,8);rows.innerHTML=(m.map((x,i)=>row(k,x,i+1)).join("")||"")+catalogue.map(x=>`<div class="row"><div class="num">+</div><div><div class="title">${esc(x.title)}</div><div class="meta">${esc(x.genre)}</div><button class="ctrl on" onclick="manual('${k}','${x.id}')">Add to my ${cfg(k).name}</button></div></div>`).join("")+(m.length||catalogue.length?"":`<div class="empty small">No local match — checking online…</div>`);clearTimeout(searchTimer);let seq=++searchSeq;searchTimer=setTimeout(()=>onlineSearch(k,q,seq),350)}
function render(){let app=document.getElementById("app");if(view==="home"){app.innerHTML=`<div class="home"><div class="brand"><small>H & F</small><h1>HUNDO & FIDDY</h1><p>What are we watching?</p></div><div class="choices"><button class="choice" onclick="go('movie')"><small>Movies</small><b>Movie Hundo</b><span>Your next 100 films →</span></button><button class="choice" onclick="go('tv')"><small>TV</small><b>TV Fiddy</b><span>Your next 50 series →</span></button></div><button class="icon" style="margin:40px auto 0" onclick="settings()">Settings</button></div>`;return}let k=view,c=cfg(k),s=st(k);if(tab==="history"){let h=hist(k);app.innerHTML=`<div class="shell"><div class="top"><button class="icon" onclick="view='home';render()">⌂</button><h1>${c.name}</h1><div class="sp"></div><button class="icon" onclick="settings()">⚙</button></div><div class="tabs"><button class="tab" onclick="tab='list';render()">My List</button><button class="tab on">History</button></div><div>${h.length?h.map(x=>histrow(k,x)).join(""):`<div class="empty">Nothing watched yet.</div>`}</div></div>`;return}let arr=s.phase==="setup"?all(k).slice(0,40):s.list.map(id=>all(k).find(x=>x.id===id)).filter(Boolean),answered=all(k).slice(0,40).filter(x=>A(k,x.id).status).length;app.innerHTML=`<div class="shell"><div class="top"><button class="icon" onclick="view='home';render()">⌂</button><h1>${c.name}</h1><div class="sp"></div><button class="icon" onclick="settings()">⚙</button></div><div class="tabs"><button class="tab on">My List</button><button class="tab" onclick="tab='history';render()">History</button></div>${s.phase==="setup"?`<div class="sub">Taste setup · 40 quick picks, then your personalised ${c.size}.</div><span class="stat">${answered}/40 answered</span><div class="progress"><i style="width:${answered/40*100}%"></i></div>`:`<div class="sub">Round ${s.round} · rate, comment and refine as you go.</div>`}<input class="search" placeholder="${s.phase==="setup"?"Search these 40 or find any title online…":"Search your list or add any title online…"}" oninput="search('${k}',this.value)"><div id="rows">${arr.map((x,i)=>row(k,x,i+1)).join("")}</div></div><div class="bottom"><button onclick="backup()">Backup</button><button class="primary" onclick="regen('${k}')">${s.phase==="setup"?"Generate My "+c.size:"Generate New "+c.size}</button></div>`}
